package kk.qisheng.talkrobot.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import kk.qisheng.talkrobot.db.TalkMsg;

import kk.qisheng.talkrobot.db.TalkMsgDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig talkMsgDaoConfig;

    private final TalkMsgDao talkMsgDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        talkMsgDaoConfig = daoConfigMap.get(TalkMsgDao.class).clone();
        talkMsgDaoConfig.initIdentityScope(type);

        talkMsgDao = new TalkMsgDao(talkMsgDaoConfig, this);

        registerDao(TalkMsg.class, talkMsgDao);
    }
    
    public void clear() {
        talkMsgDaoConfig.clearIdentityScope();
    }

    public TalkMsgDao getTalkMsgDao() {
        return talkMsgDao;
    }

}
